/// The type of file being generated.
enum FileType {
  /// A user-facing service class.
  service,

  /// A generated base service class.
  serviceBase,

  /// A generated test file.
  test,

  /// Any other type of file.
  other,
}

/// Represents a file to be generated by the service generator.
class GeneratedFileModel {
  /// Creates a [GeneratedFileModel].
  GeneratedFileModel({
    required this.fileName,
    required this.content,
    required this.type,
    this.isCustom = false,
    this.subDir = '',
  });

  /// The name of the file to be generated.
  final String fileName;

  /// The string content of the file.
  final String content;

  /// The relative sub-directory where the file should be placed.
  final String subDir;

  /// The type of the file.
  final FileType type;

  /// Whether the file is a custom (non-generated-base) file.
  final bool isCustom;
}
